# Generated by Django 5.0.4 on 2024-05-02 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_course_fileuploadquestion_multiplechoicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
